common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails_app


development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production
