common: &common
  adapter: mysql2
  username: root
  host: localhost

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production
